# Generated by Django 2.2.12 on 2022-02-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='time',
            field=models.IntegerField(default=259200, verbose_name='处理时限(s)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(default='G20220301000109', max_length=15, unique=True, verbose_name='工单编号'),
        ),
    ]
