# Generated by Django 2.2.12 on 2022-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20220302_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(default='G20220309190357', max_length=18, unique=True, verbose_name='工单编号'),
        ),
    ]
