# Generated by Django 2.2.12 on 2022-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20220309_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(default='G20220309193857', max_length=18, unique=True, verbose_name='工单编号'),
        ),
    ]
