# Generated by Django 2.2.12 on 2022-03-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20220309_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(default='G20220309215408', max_length=18, unique=True, verbose_name='工单编号'),
        ),
    ]
