# Generated by Django 2.2.12 on 2022-03-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20220309_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='file',
            field=models.FileField(default=None, upload_to='good_files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(default='G20220309231023', max_length=18, unique=True, verbose_name='工单编号'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名')),
                ('isimg', models.BooleanField(verbose_name='是图片')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'files',
            },
        ),
    ]
