# Generated by Django 2.2.12 on 2022-03-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20220309_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='file',
        ),
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(default='G20220309231231', max_length=18, unique=True, verbose_name='工单编号'),
        ),
    ]
