# Generated by Django 2.2.12 on 2022-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20220309_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(null=True, upload_to='updataFiles'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(default='G20220309232018', max_length=18, unique=True, verbose_name='工单编号'),
        ),
    ]
