# Generated by Django 2.2.12 on 2022-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('number', models.CharField(max_length=11, verbose_name='手机号')),
                ('level', models.CharField(default=1, max_length=1, verbose_name='级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
