# Generated by Django 2.2.12 on 2022-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_photo',
            field=models.FileField(default='', upload_to='headPhoto'),
        ),
    ]
