# Generated by Django 2.2.12 on 2022-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_head_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_photo',
            field=models.FileField(default='/headPhoto/bdd.jpg', upload_to='headPhoto'),
        ),
    ]
